version: '3.6'

services:
    postgres:
        image: debezium/postgres:latest
        restart: always
        container_name: debezium-postgres
        environment:
          POSTGRES_PASSWORD: marvel
          POSTGRES_USER: marvel
          POSTGRES_DB: nap-poc
        ports:
          - 5432:5432
        command: [ "postgres", "-c", "wal_level=logical" ]        
