version: '3.6'

services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: mahendran-postgres
        environment:
          POSTGRES_PASSWORD: marvel
          POSTGRES_USER: marvel
          POSTGRES_DB: nap-poc
        ports:
          - 5432:5432
        volumes:
          - database-data:/var/lib/postgresql/data
volumes:
  database-data: