#!/usr/bin/env bash
echo Starting create DynamoDB Table...
./src/main/shell/dynamoDB.sh createTable
echo Starting register schemas...
./src/main/shell/registerSchemas.sh
echo Starting create Kafka topics...
./src/main/shell/createKafkaTopics.sh

